/**
 * Generation of the `devperf_report` custom tool (docs/design.md §6.5,
 * plan step 7): `buildReportToolSource` renders the plugin source that
 * is written into the analyzed clone's `.opencode/tools/` directory and
 * loaded by the opencode server at startup.
 *
 * The tool's argument schema is derived from the shared report schema
 * (`llmToolPayloadSchema`), so the model-facing shape cannot drift from
 * the report. The generated file is self-contained: it imports only
 * `@opencode-ai/plugin` (resolved by the opencode runtime itself, not
 * from dev-perf's node_modules) and `node:` builtins, defines the
 * payload schema with `tool.schema` (the plugin's zod), validates the
 * payload with it, and writes the result to
 * `<cache>/<hash>/llm/<sessionID>.json` — the orchestrator maps
 * sessions to users (plan step 8), so the tool never needs to know the
 * analyzed user's key.
 */
import { z } from 'zod';
import { llmToolPayloadSchema } from '../report/index.js';

/** Model-facing description of the `devperf_report` tool. */
const TOOL_DESCRIPTION =
  "Reports the final dev-perf analysis for the user analyzed in this session: an optional overview and the user's changes split into distinct contributions (one feature, one bug fix, one refactor, and so on). Call this tool with the complete analysis before finishing the session; no other output format is accepted.";

/**
 * The subset of JSON Schema shapes the report schema uses; anything
 * else makes the renderer fail fast instead of emitting broken code.
 */
interface JsonSchemaShape {
  /** JSON Schema type keyword. */
  type?: string;
  /** Description from a `.describe()` call, if any. */
  description?: string;
  /** Enum values for string schemas. */
  enum?: string[];
  /** Named properties for object schemas. */
  properties?: Record<string, JsonSchemaShape>;
  /** Names of the object's required properties. */
  required?: string[];
  /** Item schema for array schemas. */
  items?: JsonSchemaShape;
}

/**
 * Renders one JSON Schema value as a `tool.schema.*` expression, e.g.
 * `tool.schema.string().describe("...")` or
 * `tool.schema.array(tool.schema.enum(["feature", "bugfix"]))`.
 * Descriptions are emitted as `.describe()` calls so the model sees
 * every field's meaning; a property is optional when its name is
 * missing from the enclosing object's `required` list.
 *
 * @param shape - The JSON Schema shape to render.
 * @param indent - Indentation prefix for nested expressions.
 * @returns The rendered zod source expression.
 * @throws {Error} For shapes outside the supported subset.
 */
function renderValue(shape: JsonSchemaShape, indent: string): string {
  let expression: string;
  if (shape.type === 'object') {
    const fields = Object.entries(shape.properties ?? {});
    const requiredNames = shape.required ?? [];
    if (fields.length === 0) {
      expression = 'tool.schema.object({})';
    } else {
      const inner = indent + '  ';
      const body = fields
        .map(([name, field]) => {
          const optional = !requiredNames.includes(name);
          return `${inner}${JSON.stringify(name)}: ${renderValue(field, inner)}${optional ? '.optional()' : ''}`;
        })
        .join(',\n');
      expression = `tool.schema.object({\n${body},\n${indent}})`;
    }
  } else if (shape.type === 'array') {
    if (shape.items === undefined) {
      throw new Error('array schema without items');
    }
    expression = `tool.schema.array(${renderValue(shape.items, indent)})`;
  } else if (shape.type === 'string' && shape.enum !== undefined) {
    expression = `tool.schema.enum(${JSON.stringify(shape.enum)})`;
  } else if (shape.type === 'string') {
    expression = 'tool.schema.string()';
  } else if (shape.type === 'number' || shape.type === 'integer') {
    expression = 'tool.schema.number()';
  } else if (shape.type === 'boolean') {
    expression = 'tool.schema.boolean()';
  } else {
    throw new Error(`unsupported JSON schema shape: ${JSON.stringify(shape.type)}`);
  }
  if (shape.description !== undefined) {
    expression += `.describe(${JSON.stringify(shape.description)})`;
  }
  return expression;
}

/**
 * Renders the full plugin source of the `devperf_report` tool for a
 * given LLM results directory. The tool name comes from the file name
 * (`devperf_report.ts`), so the source only exports the default tool.
 *
 * @param llmDir - Absolute path of the `<cache>/<hash>/llm/` directory
 * the tool writes its report files to.
 * @returns The TypeScript source of `.opencode/tools/devperf_report.ts`.
 */
export function buildReportToolSource(llmDir: string): string {
  const payloadShape = renderValue(z.toJSONSchema(llmToolPayloadSchema) as JsonSchemaShape, '');
  return [
    '// Generated by dev-perf (docs/design.md §6.5); do not edit. This file',
    '// is regenerated on every LLM server start and loaded by the opencode',
    "// server from the analyzed clone's .opencode/tools/ directory.",
    'import { tool } from "@opencode-ai/plugin";',
    'import path from "node:path";',
    'import { mkdir, writeFile } from "node:fs/promises";',
    '',
    `const REPORT_DIR = ${JSON.stringify(llmDir)};`,
    '',
    `const payloadSchema = ${payloadShape};`,
    '',
    `export default tool({`,
    `  description: ${JSON.stringify(TOOL_DESCRIPTION)},`,
    '  args: payloadSchema.shape,',
    '  async execute(args, context) {',
    '    const parsed = payloadSchema.safeParse(args);',
    '    if (!parsed.success) {',
    '      return `devperf_report: invalid analysis payload: ${parsed.error.message}`;',
    '    }',
    '    await mkdir(REPORT_DIR, { recursive: true });',
    '    const file = path.join(REPORT_DIR, `${context.sessionID}.json`);',
    '    await writeFile(file, JSON.stringify(parsed.data, null, 2), "utf8");',
    '    return "ok";',
    '  },',
    '});',
    '',
  ].join('\n');
}
